source_root: ./examples/source
target_root: ./examples/target
operation: copy
archive_root: ./examples/archive
photo_extensions:
  - jpg
  - jpeg
  - png
dir_pattern: "{asset_type}/{new_tag}"
filename_pattern: "{new_tag}_{idx:03d}.{ext}"
report_dir: ./examples/reports
